#common 通用

spring:
  redis:
    host: 192.168.68.123
    password:
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.68.123:3306/online-taxi?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: dev1101
    password: dev1101
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,slf4j
      initialSize: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      useGlobalDataSourceStat: true
      validationQuery: SELECT 'x'
  activemq:
    broker-url: tcp://192.168.33.239:61617
    in-memory: false
    pool:
      enabled: true
      max-connections: 100

services:
  address:
    - account: http://localhost:8081
    - dispatch: http://localhost:8082
    - order: http://localhost:8083
    - map: http://localhost:8084
    - message: http://localhost:8085
    - netty: http://localhost:8086
    - pay: http://localhost:8087
    - valuation: http://localhost:8088
    - file: http://localhost:8089
    - government: http://localhost:9999

#internal 程序内部
logging:
  config: classpath:log/logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

pagehelper:
  reasonable: true

#customer
apikey:
  ali:
    - pool_key: FC10000xxxxxxxxxx
    - file_path: tmp
    - key_id: LTAIoCxxxxxxxxxx
    - key_secret: jPtxnruaZGJ7Hjbxxxxxxxxxxxxxxx
    - dyplsapi: Dyplsapi
    - domain: dyplsapi.aliyuncs.com

  oss:
    - endpoint: https://oss-cn-hangzhou.aliyuncs.com/
    - access_id: LTAIzbxxxxxxxxxxx
    - access_key: c3rLTtLv4qxxxxxxxxxxxxxxxxxxxx
    - bucket_lkmotion: xxxxxxxx-test-source
    - oss_file_name: voiceRecording
    - role_arn: acs:ram::114191xxxxxxxxxx:role/xxxxxx-test-source-write
